### ISSUE TITLE
upgrade to 0.2.5,some website doesn't work!

### ISSUE THREAD

**Issue by hippora** [belaviyo/keepass-macpass-helper#11] opened 2017-08-21 04:19 UTC
chrome,macpass 0.6.2 with lastest macpasshttp,
example site:
https://qiye.aliyun.com/
https://exmail.qq.com/cgi-bin/loginpage
https://account.aliyun.com/login/login.htm
...
0.2.4works fine,please fix it

**Comment by belaviyo** [comment] 2017-08-21 06:20
I am not sure what the problem is. It is not displaying credentials?

**Comment by hippora** [comment] 2017-08-21 08:25
no,i press cmd+k to display credentials panel, then i press cmd+b to fill both username and password,but didn't work ,(https://exmail.qq.com/cgi-bin/loginpage) can fill usename ,but fill the wrong password, i don't know why.

**Comment by belaviyo** [comment] 2017-08-21 08:57
Okay, got it. It is now fixed on 0.1.6. Please wait for the update. Thanks for the report.

**Closed** 2017-08-21 08:56 UTC

**Comment by hippora** [comment] 2017-08-21 16:47
Would you like to take a look at this site?(https://account.aliyun.com/login/login.htm),it have a iframe.(china's website is complicated ).also i press cmd+k, cmd+b, nothing happened.
last version works fine . My keepass's record URL is: https://account.aliyun.com/login/login.htm.
and Only this extension can filter my records correctly,That's why i like use this extension.(chromi
Thank you for your patience.

**Comment by belaviyo** [comment] 2017-08-22 05:42
Thanks! it is now fixed on 0.2.7. Well, I had a few optimizations in 0.2.5 and turned out that all I did was messing up with the extension :).
